### ISSUE TITLE
Error 500 - Shopify Install App failing

### ISSUE THREAD

**Issue by yashodhank** [frappe/erpnext_shopify_broker#12]
Steps to reproduce (Logged into Store Backend):

https://apps.shopify.com/search/query?utf8=%E2%9C%93&q=erpnext
https://apps.shopify.com/erpnext
https://apps.shopify.com/erpnext/install

Originally Posted at:https://github.com/frappe/erpnext_shopify/issues/160

```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2016-07-23/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.api.handle()
  File "/home/frappe/benches/bench-2016-07-23/apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "/home/frappe/benches/bench-2016-07-23/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-2016-07-23/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2016-07-23/apps/frappe/frappe/__init__.py", line 913, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2016-07-23/apps/erpnext_shopify_broker/erpnext_shopify_broker/erpnext_shopify_broker/doctype/broker_settings/broker_settings.py", line 55, in generate_token
    res = requests.post(url= url, data=json.dumps(token_dict), headers={'Content-type': 'application/json'})
  File "/home/frappe/benches/bench-2016-07-23/env/lib/python2.7/site-packages/requests/api.py", line 111, in post
  File "/home/frappe/benches/bench-2016-07-23/env/lib/python2.7/site-packages/requests/api.py", line 57, in request
    with sessions.Session() as session:
  File "/home/frappe/benches/bench-2016-07-23/env/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    # Create the Request.
  File "/home/frappe/benches/bench-2016-07-23/env/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
  File "/home/frappe/benches/bench-2016-07-23/env/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    r,
SSLError: [Errno 2] No such file or directory
Home
```

- https://user-images.githubusercontent.com/1083792/27759551-efc1e9d6-5e50-11e7-8d0e-4efab5885ff6.png
- https://user-images.githubusercontent.com/1083792/27759440-af61f4aa-5e4e-11e7-9428-d1b3554f71cf.png

**Comment by yashodhank** [comment]
<img width="1654" alt="screen shot 2017-07-09 at 1 56 25 am" src="https://user-images.githubusercontent.com/1083792/27988820-e5dc51fa-6449-11e7-8cef-644f363feb76.png">

**Issue persist error 500 visible on console.**

**Comment by yashodhank** [comment]
![image](https://user-images.githubusercontent.com/1083792/27988858-3712c31a-644a-11e7-98f6-0732ca00a450.png)
